<?php
$res = array(
'Insert_FH' => 'Inserir',
'Update_FH' => 'Atualizar',
'Record_FH' => 'Registro',
'Insert_FB' => 'Inserir',
'Update_FB' => 'Atualizar',
'Delete_FB' => 'Excluir',
'Cancel_FB' => 'Cancelar',
'Insert as new_FB' => 'Inserir c&oacute;pia',
'Select one...' => 'Selecione um(a)...',
'Are you sure?' => 'Voc&ecirc; tem certeza?',
'Filter' => 'Filtrar',
'Show' => 'Exibir',
'all' => 'todos',
'records' => 'registros',
'Reset filter' => 'Cancelar filtro',
'Show filter' => 'Exibir filtro',
'Order' => 'Ordenar',
'save' => 'Salvar',
'None' => 'Nenhum',
'The table is empty or the filter you\'ve selected is too restrictive.' => 'A tabela est&aacute; vazia ou o filtro &eacute; excessivamente restritivo.',
'edit_one' => 'editar',
'delete_one' => 'excluir',
'edit_all' => 'editar',
'delete_all' => 'excluir',
'add new' => 'adicionar novo',
'ARE_YOU_SURE_MOVE' => 'Você modificou a ordem de alguns registro e não salvou as alterações. Se você continuar, as alterações feitas serão perdidas.',
'ARE_YOU_SURE_DELETE' => 'Você tem certeza que deseja excluir estes registros?',
'PLEASE_SELECT_RECORD' => 'Por favor, selecione pelo menos um registro.',
'to' => '&agrave;',
'of' => 'de',
'First' => 'In&iacute;cio',
'Previous' => 'Anterior',
'Next' => 'Seguinte',
'Last' => 'Final',
);
?>